target_process = "icad.exe"
core_selections = [false, false, false, false, true, true, false, false, false, false, false, false]
priority_class = 32768

[[processes]]
name = "icad.exe"
core_selections = [false, false, false, false, true, true, false, false, false, false, false, false]
priority_class = 32768
enabled = true

[[processes]]
name = "qwerty.exe"
core_selections = [false, false, false, false, true, true, false, false, false, false, false, false]
priority_class = 32768
enabled = true
